# Overview

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
path_1 = "https://drive.google.com/uc?export=download&id=1LuplQM6VNQFzuZPKeTahsXG6Ao4pCerp"
path_2 = "https://drive.google.com/uc?export=download&id=1omkopBSesGSPhSFz7xXubeJ_NUl0o2SI"
path_3 = "https://drive.google.com/uc?export=download&id=1Epmlp1d-QVN3G3xySAjV8WhfqsOylZcp"
path_4 = "https://drive.google.com/uc?export=download&id=1mse23AkW0D2A9YU7QfpBn9ILDAtUv-gq"
path_5 = "https://drive.google.com/uc?export=download&id=1UpBcIzRru4Zd_0YE5M5nhr-SYIDbOu2G"

df_1 = pd.read_csv(path_1)
df_2 = pd.read_csv(path_2)
df_3 = pd.read_csv(path_3)
df_4 = pd.read_csv(path_4)
df_5 = pd.read_csv(path_5)

## Business_outcomes Check

In [ ]:
display(df_1.head())

,Store_Id,Department,Year_Month,Sales_Target,Sales_Actual,Customer_Satisfaction,Nps_Score,Waste_Percentage,On_Time_Delivery
0,STR001,Store Operations,2022-01,153000,164399.59,7.4,47.0,0.73,98.6
1,STR001,Fresh Produce,2022-01,38250,39851.00,8.5,51.5,2.73,92.4
2,STR001,Meat/Fish & Bakery,2022-01,29750,30829.76,5.6,-24.1,3.64,92.3
3,STR002,Store Operations,2022-01,153000,143176.34,6.8,14.6,1.68,87.6
4,STR002,Fresh Produce,2022-01,38250,38637.44,6.1,3.3,4.43,94.3

In [ ]:
display(df_1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16200 entries, 0 to 16199
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_Id               16200 non-null  object
 1   Department             16200 non-null  object
 2   Year_Month             16200 non-null  object
 3   Sales_Target           16200 non-null  int64
 4   Sales_Actual           16200 non-null  float64
 5   Customer_Satisfaction  16200 non-null  float64
 6   Nps_Score              16200 non-null  float64
 7   Waste_Percentage       16200 non-null  float64
 8   On_Time_Delivery       16200 non-null  float64
dtypes: float64(5), int64(1), object(3)
memory usage: 1.1+ MB

None

- Year_Month obj -> date

In [ ]:
display(df_1.describe())
display(df_1.describe(include = 'object'))

,Sales_Target,Sales_Actual,Customer_Satisfaction,Nps_Score,Waste_Percentage,On_Time_Delivery
count,16200.000000,16200.000000,16200.000000,16200.000000,16200.000000,16200.000000
mean,122122.337037,122193.018657,7.500284,40.119006,2.835536,93.979975
std,111447.195395,114597.712846,0.988154,24.723058,1.482315,2.945439
min,17850.000000,11148.860000,3.500000,-56.500000,0.500000,80.600000
25%,45500.000000,43763.495000,6.800000,23.200000,1.580000,92.000000
50%,69300.000000,70502.905000,7.500000,40.400000,2.680000,94.000000
75%,180000.000000,171523.280000,8.200000,57.000000,4.072500,96.000000
max,589680.000000,746030.660000,10.000000,100.000000,6.000000,100.000000

       Store_Id        Department Year_Month
count     16200             16200      16200
unique      150                 3         36
top      STR001  Store Operations    2022-01
freq        108              5400        450

In [ ]:
display(df_1.duplicated().sum())

np.int64(0)

In [ ]:
df_1['Year_Month'] = pd.to_datetime(df_1['Year_Month'])
df_1['Year'] = df_1['Year_Month'].dt.year
df_1['Month'] = df_1['Year_Month'].dt.month

## Employees Check

In [ ]:
display(df_2.head())

,Employee_Id,Full_Name,Age,Education_Level,Hire_Date,Exit_Date,Department,Job_Role,Job_Level,Employment_Type,Base_Salary_Annual,Store_Location,Store_Location_Latitude,Store_Location_Longitude,Store_Id,Manager_Id,Manager_Name,Manager_Status
0,EMP000001,Marie Kim DDS,23,Master's,26/04/2021,13/04/2022,Store Operations,Cashier,Entry,Full-time,25745.40,Charlotte,35.2271,-80.8431,STR058,EMP001131,Michelle Walls,Executive
1,EMP000002,Danny Morgan,26,Master's,03/09/2021,NaN,Store Operations,Sales Associate,Associate,Full-time,39408.57,San Jose,37.3382,-121.8863,STR137,EMP002456,Jennifer Moore,Executive
2,EMP000003,Crystal Robinson,38,Bachelor's,25/08/2016,NaN,Store Operations,Cashier,Entry,Full-time,29319.94,Jacksonville,30.3322,-81.6557,STR008,EMP000529,Melissa Bishop,Senior Manager
3,EMP000004,Mark Perez,33,Bachelor's,10/12/2021,NaN,Store Operations,Senior Sales Associate,Senior_Associate,Full-time,43979.88,Las Vegas,36.1699,-115.1398,STR063,EMP001305,Tina Walter,Senior Manager
4,EMP000005,Shannon Jones,24,High School,24/02/2018,NaN,Store Operations,Cashier,Entry,Full-time,23560.19,Chicago,41.8781,-87.6298,STR109,EMP001823,Nicholas Fitzgerald,Senior Manager

In [ ]:
display(df_2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Employee_Id               7500 non-null   object
 1   Full_Name                 7500 non-null   object
 2   Age                       7500 non-null   int64
 3   Education_Level           7500 non-null   object
 4   Hire_Date                 7500 non-null   object
 5   Exit_Date                 1491 non-null   object
 6   Department                7500 non-null   object
 7   Job_Role                  7500 non-null   object
 8   Job_Level                 7500 non-null   object
 9   Employment_Type           7500 non-null   object
 10  Base_Salary_Annual        7500 non-null   float64
 11  Store_Location            7500 non-null   object
 12  Store_Location_Latitude   7500 non-null   float64
 13  Store_Location_Longitude  7500 non-null   float64
 14  Store_Id                  7500 non-null   object
 15  Manager_Id                7495 non-null   object
 16  Manager_Name              7495 non-null   object
 17  Manager_Status            7495 non-null   object
dtypes: float64(3), int64(1), object(14)
memory usage: 1.0+ MB

None

In [ ]:
bossless_employees = df_2[df_2['Manager_Id'].isnull()]
print(bossless_employees[['Employee_Id', 'Full_Name', 'Job_Level', 'Job_Role']])

     Employee_Id          Full_Name  Job_Level                 Job_Role
1130   EMP001131     Michelle Walls  Executive  Chief Operating Officer
2455   EMP002456     Jennifer Moore  Executive  Chief Operating Officer
3939   EMP003940  Victoria Marshall  Executive           Vice President
6821   EMP006822    Lauren Thompson  Executive  Chief Financial Officer
7273   EMP007274          Cory Hale  Executive           Vice President

- Hire_Date, Exit_Date obj -> date
- Exit_Date null bởi vì nhân viên vẫn còn đang làm
- Manager_Id, Manager_Name, Manager_Status null 5 vì 5 người đều thuộc nhóm Executive

In [ ]:
display(df_2.describe())
display(df_2.describe(include = 'object'))

,Age,Base_Salary_Annual,Store_Location_Latitude,Store_Location_Longitude
count,7500.000000,7500.000000,7500.000000,7500.000000
mean,32.450000,27253.855732,36.954572,-96.160918
std,7.482319,10217.242704,4.878566,16.457037
min,21.000000,8823.460000,29.424100,-122.678400
25%,27.000000,19899.520000,32.776700,-112.074000
50%,32.000000,27394.165000,36.169900,-95.369800
75%,37.000000,31945.697500,39.961200,-82.998800
max,64.000000,177873.610000,47.606200,-71.058900

,Employee_Id,Full_Name,Education_Level,Hire_Date,Exit_Date,Department,Job_Role,Job_Level,Employment_Type,Store_Location,Store_Id,Manager_Id,Manager_Name,Manager_Status
count,7500,7500,7500,7500,1491,7500,7500,7500,7500,7500,7500,7495,7495,7495
unique,7500,7107,5,2179,1043,9,53,7,4,25,150,50,50,3
top,EMP007500,Jennifer Smith,High School,04/01/2012,14/09/2023,Store Operations,Cashier,Entry,Full-time,Fort Worth,STR069,EMP005303,Isaiah Terry,Manager
freq,1,6,2665,91,5,3000,1610,4000,4897,330,68,168,168,4478

In [ ]:
display(df_2.duplicated().sum())

np.int64(0)

In [ ]:
df_2['Hire_Date'] = pd.to_datetime(df_2['Hire_Date'])
df_2['Exit_Date'] = pd.to_datetime(df_2['Exit_Date'])

## Monthly_performance Check

In [ ]:
display(df_3.head())

,Employee_Id,Year_Month,Performance_Rating,Training_Hours,Overtime_Hours,Absenteeism_Days,Promotion_Flag,Salary_Increase_Flag,Monthly_Bonus,Benefits_Cost,Employee_Satisfaction,Engagement_Index,Manager_Evaluation
0,EMP000001,2022-01,4.13,2,15,1,False,False,657.44,1727.09,8.0,8.1,4.5
1,EMP000002,2022-01,3.60,9,10,1,False,False,626.76,1584.89,8.0,9.1,3.6
2,EMP000003,2022-01,3.65,3,12,0,False,False,554.12,1584.56,6.3,5.1,3.5
3,EMP000004,2022-01,3.51,6,8,0,False,False,669.14,1759.48,8.1,8.0,3.3
4,EMP000005,2022-01,5.00,1,4,1,False,False,235.22,947.89,10.0,9.7,5.0

In [ ]:
display(df_3.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236591 entries, 0 to 236590
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Employee_Id            236591 non-null  object
 1   Year_Month             236591 non-null  object
 2   Performance_Rating     236591 non-null  float64
 3   Training_Hours         236591 non-null  int64
 4   Overtime_Hours         236591 non-null  int64
 5   Absenteeism_Days       236591 non-null  int64
 6   Promotion_Flag         236591 non-null  bool
 7   Salary_Increase_Flag   236591 non-null  bool
 8   Monthly_Bonus          236591 non-null  float64
 9   Benefits_Cost          236591 non-null  float64
 10  Employee_Satisfaction  236591 non-null  float64
 11  Engagement_Index       236591 non-null  float64
 12  Manager_Evaluation     236591 non-null  float64
dtypes: bool(2), float64(6), int64(3), object(2)
memory usage: 20.3+ MB

None

In [ ]:
display(df_3.describe())

,Performance_Rating,Training_Hours,Overtime_Hours,Absenteeism_Days,Monthly_Bonus,Benefits_Cost,Employee_Satisfaction,Engagement_Index,Manager_Evaluation
count,236591.000000,236591.000000,236591.000000,236591.000000,236591.000000,236591.000000,236591.000000,236591.000000,236591.000000
mean,3.701753,2.807681,8.031658,0.711637,248.604603,748.917364,7.238340,7.220323,3.700053
std,0.442421,2.273293,4.981170,0.861559,302.626752,458.760361,1.292169,1.485795,0.533884
min,1.000000,0.000000,0.000000,0.000000,10.370000,41.740000,1.000000,1.000000,1.000000
25%,3.400000,1.000000,4.000000,0.000000,65.110000,410.640000,6.400000,6.200000,3.300000
50%,3.720000,2.000000,8.000000,1.000000,124.530000,692.820000,7.200000,7.200000,3.700000
75%,4.020000,4.000000,11.000000,1.000000,314.770000,970.720000,8.100000,8.300000,4.100000
max,5.000000,27.000000,39.000000,7.000000,3762.520000,3112.500000,10.000000,10.000000,5.000000

In [ ]:
display(df_3.duplicated().sum())

np.int64(0)

In [ ]:
df_3['Year_Month'] = pd.to_datetime(df_3['Year_Month'])
df_3['Year'] = df_3['Year_Month'].dt.year
df_3['Month'] = df_3['Year_Month'].dt.month

## Role_kpis Check

In [ ]:
display(df_4.head())

,Employee_Id,Year_Month,Kpi_1_Value,Kpi_1_Name,Kpi_2_Value,Kpi_2_Name,Kpi_3_Value,Kpi_3_Name,Productivity_Index
0,EMP000001,2022-01,87.77,Task Completion Rate %,8.20,Quality Score,9.15,Efficiency Rating,1.565
1,EMP000002,2022-01,88.94,Task Completion Rate %,6.66,Quality Score,6.09,Efficiency Rating,1.302
2,EMP000003,2022-01,85.00,Store Sales vs Target %,17.37,Employee Turnover %,7.21,Customer Satisfaction,1.323
3,EMP000004,2022-01,88.51,Store Sales vs Target %,7.98,Employee Turnover %,8.60,Customer Satisfaction,1.253
4,EMP000005,2022-01,100.00,Task Completion Rate %,8.26,Quality Score,8.82,Efficiency Rating,2.000

In [ ]:
display(df_4.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236591 entries, 0 to 236590
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Employee_Id         236591 non-null  object
 1   Year_Month          236591 non-null  object
 2   Kpi_1_Value         236591 non-null  float64
 3   Kpi_1_Name          236591 non-null  object
 4   Kpi_2_Value         236591 non-null  float64
 5   Kpi_2_Name          236591 non-null  object
 6   Kpi_3_Value         236591 non-null  float64
 7   Kpi_3_Name          236591 non-null  object
 8   Productivity_Index  236591 non-null  float64
dtypes: float64(4), object(5)
memory usage: 16.2+ MB

None

In [ ]:
display(df_4.describe())

         Kpi_1_Value    Kpi_2_Value    Kpi_3_Value  Productivity_Index
count  236591.000000  236591.000000  236591.000000       236591.000000
mean      143.986892      20.165928      21.092766            1.350878
std       226.427191      29.638375      78.520609            0.221203
min         0.500000       0.000000       0.000000            0.000000
25%        78.920000       6.670000       4.460000            1.202000
50%        86.840000       7.730000       6.470000            1.361000
75%        95.700000       9.690000       7.710000            1.509000
max      1400.000000     100.000000     650.000000            2.000000

In [ ]:
display(df_4.duplicated().sum())

np.int64(0)

In [ ]:
df_4['Year_Month'] = pd.to_datetime(df_4['Year_Month'])
df_4['Year'] = df_4['Year_Month'].dt.year
df_4['Month'] = df_4['Year_Month'].dt.month

## Stores Check

In [ ]:
display(df_5.head())

,Store_Id,Store_Name,City,City_Latitude,City_Longitude,Store_Type,Opening_Date
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021
1,STR002,Charlotte Regular #2,Charlotte,35.2271,-80.8431,Regular,09/11/2015
2,STR003,Portland Superstore #3,Portland,45.5152,-122.6784,Superstore,08/02/2018
3,STR004,Nashville Superstore #4,Nashville,36.1627,-86.7816,Superstore,21/08/2017
4,STR005,Austin Regular #5,Austin,30.2672,-97.7431,Regular,04/04/2022

In [ ]:
display(df_5.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Store_Id        150 non-null    object
 1   Store_Name      150 non-null    object
 2   City            150 non-null    object
 3   City_Latitude   150 non-null    float64
 4   City_Longitude  150 non-null    float64
 5   Store_Type      150 non-null    object
 6   Opening_Date    150 non-null    object
dtypes: float64(2), object(5)
memory usage: 8.3+ KB

None

In [ ]:
display(df_5.duplicated().sum())

np.int64(0)

In [ ]:
df_5['Opening_Date'] = pd.to_datetime(df_5['Opening_Date'])
df_5['Year'] = df_5['Opening_Date'].dt.year
df_5['Month'] = df_5['Opening_Date'].dt.month
df_5['Day'] = df_5['Opening_Date'].dt.day

# EDA & PROCESSING

## Business_outcomes

In [ ]:
df_1.head()

,Store_Id,Department,Year_Month,Sales_Target,Sales_Actual,Customer_Satisfaction,Nps_Score,Waste_Percentage,On_Time_Delivery,Year,Month
0,STR001,Store Operations,2022-01-01,153000,164399.59,7.4,47.0,0.73,98.6,2022,1
1,STR001,Fresh Produce,2022-01-01,38250,39851.00,8.5,51.5,2.73,92.4,2022,1
2,STR001,Meat/Fish & Bakery,2022-01-01,29750,30829.76,5.6,-24.1,3.64,92.3,2022,1
3,STR002,Store Operations,2022-01-01,153000,143176.34,6.8,14.6,1.68,87.6,2022,1
4,STR002,Fresh Produce,2022-01-01,38250,38637.44,6.1,3.3,4.43,94.3,2022,1

In [ ]:
df_1['Sales_Target_Achievement_Pct'] = (df_1['Sales_Actual'] / df_1['Sales_Target'] * 100).round(2)
print(df_1[['Store_Id', 'Year_Month', 'Sales_Target', 'Sales_Actual', 'Sales_Target_Achievement_Pct']].head())

  Store_Id Year_Month  Sales_Target  Sales_Actual  \
0   STR001 2022-01-01        153000     164399.59
1   STR001 2022-01-01         38250      39851.00
2   STR001 2022-01-01         29750      30829.76
3   STR002 2022-01-01        153000     143176.34
4   STR002 2022-01-01         38250      38637.44

   Sales_Target_Achievement_Pct
0                        107.45
1                        104.19
2                        103.63
3                         93.58
4                        101.01

## Employees

In [ ]:
# Xử lý 5 sếp lớn
df_2['Manager_Id'] = df_2['Manager_Id'].fillna('BOD')
df_2['Manager_Name'] = df_2['Manager_Name'].fillna('Board Of Directors')
df_2['Manager_Status'] = df_2['Manager_Status'].fillna('Active')

In [ ]:
# Trạng thái làm việc & thâm niên
df_2['Is_Active'] = df_2['Exit_Date'].isnull()

report_date = pd.to_datetime('2024-12-31')
df_2['Tenure_Days'] = (df_2['Exit_Date'].fillna(report_date) - df_2['Hire_Date']).dt.days

df_2['Exit_YearMonth'] = df_2['Exit_Date'].dt.to_period('M')
display(df_2.head())

,Employee_Id,Full_Name,Age,Education_Level,Hire_Date,Exit_Date,Department,Job_Role,Job_Level,Employment_Type,...,Store_Location,Store_Location_Latitude,Store_Location_Longitude,Store_Id,Manager_Id,Manager_Name,Manager_Status,Is_Active,Tenure_Days,Exit_YearMonth
0,EMP000001,Marie Kim DDS,23,Master's,2021-04-26,2022-04-13,Store Operations,Cashier,Entry,Full-time,...,Charlotte,35.2271,-80.8431,STR058,EMP001131,Michelle Walls,Executive,False,352,2022-04
1,EMP000002,Danny Morgan,26,Master's,2021-09-03,NaT,Store Operations,Sales Associate,Associate,Full-time,...,San Jose,37.3382,-121.8863,STR137,EMP002456,Jennifer Moore,Executive,True,1215,NaT
2,EMP000003,Crystal Robinson,38,Bachelor's,2016-08-25,NaT,Store Operations,Cashier,Entry,Full-time,...,Jacksonville,30.3322,-81.6557,STR008,EMP000529,Melissa Bishop,Senior Manager,True,3050,NaT
3,EMP000004,Mark Perez,33,Bachelor's,2021-12-10,NaT,Store Operations,Senior Sales Associate,Senior_Associate,Full-time,...,Las Vegas,36.1699,-115.1398,STR063,EMP001305,Tina Walter,Senior Manager,True,1117,NaT
4,EMP000005,Shannon Jones,24,High School,2018-02-24,NaT,Store Operations,Cashier,Entry,Full-time,...,Chicago,41.8781,-87.6298,STR109,EMP001823,Nicholas Fitzgerald,Senior Manager,True,2502,NaT

In [ ]:
max_age = df_2['Age'].max()
print(f'Max age: {max_age}')

Max age: 64

In [ ]:
# Tạo bin tuổi
age_bins = [0,25,40,65]
age_labels = ['Gen Z', 'Millennial', 'Gen X']
df_2['Age_Group'] = pd.cut(df_2['Age'], bins = age_bins, labels = age_labels)
df_2[['Age','Age_Group']]

      Age   Age_Group
0      23       Gen Z
1      26  Millennial
2      38  Millennial
3      33  Millennial
4      24       Gen Z
...   ...         ...
7495   42       Gen X
7496   26  Millennial
7497   26  Millennial
7498   30  Millennial
7499   34  Millennial

[7500 rows x 2 columns]

## Monthly_performance

In [ ]:
df_3.head()

,Employee_Id,Year_Month,Performance_Rating,Training_Hours,Overtime_Hours,Absenteeism_Days,Promotion_Flag,Salary_Increase_Flag,Monthly_Bonus,Benefits_Cost,Employee_Satisfaction,Engagement_Index,Manager_Evaluation,Year,Month
0,EMP000001,2022-01-01,4.13,2,15,1,False,False,657.44,1727.09,8.0,8.1,4.5,2022,1
1,EMP000002,2022-01-01,3.60,9,10,1,False,False,626.76,1584.89,8.0,9.1,3.6,2022,1
2,EMP000003,2022-01-01,3.65,3,12,0,False,False,554.12,1584.56,6.3,5.1,3.5,2022,1
3,EMP000004,2022-01-01,3.51,6,8,0,False,False,669.14,1759.48,8.1,8.0,3.3,2022,1
4,EMP000005,2022-01-01,5.00,1,4,1,False,False,235.22,947.89,10.0,9.7,5.0,2022,1

In [ ]:
print(f"Thời gian đào tạo thấp nhất: {df_3['Training_Hours'].min()}")
print(f"Thời gian đào tạo cao nhất: {df_3['Training_Hours'].max()}")

Thời gian đào tạo thấp nhất: 0
Thời gian đào tạo cao nhất: 27

In [ ]:
from pandas.core.reshape.tile import cut
bin_training = [-1,0.1,8,16,30]
training_labels = ['No Training (0h)', 'Basic (1-8h)', 'Advanced (9-16h)', 'Intensive (>16h)']
df_3['Training_Group'] = pd.cut(df_3['Training_Hours'], bins = bin_training, labels = training_labels)
df_3['Training_Group']

0             Basic (1-8h)
1         Advanced (9-16h)
2             Basic (1-8h)
3             Basic (1-8h)
4             Basic (1-8h)
                ...
236586        Basic (1-8h)
236587        Basic (1-8h)
236588        Basic (1-8h)
236589        Basic (1-8h)
236590        Basic (1-8h)
Name: Training_Group, Length: 236591, dtype: category
Categories (4, object): ['No Training (0h)' < 'Basic (1-8h)' < 'Advanced (9-16h)' < 'Intensive (>16h)']

## Download

In [ ]:
df_1.to_csv('clean_business_outcomes.csv', index=False)
df_2.to_csv('clean_employees.csv', index=False)
df_3.to_csv('clean_monthly_performance.csv', index=False)
df_4.to_csv('clean_role_kpis.csv', index=False)
df_5.to_csv('clean_stores.csv', index=False)